# Generated by Django 5.0.4 on 2024-05-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastromodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('senha', models.CharField(max_length=50, verbose_name='senha')),
                ('data_nasc', models.DateField(verbose_name='data_nasc')),
            ],
        ),
    ]
