# Generated by Django 5.0.4 on 2024-06-12 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
