# Generated by Django 5.0.4 on 2024-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doacao_descricao_doacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='quantidade_doada',
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cadastromodel',
            name='senha',
            field=models.CharField(max_length=50, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='item_doado',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Item Doado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacao',
            name='ong_nome',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome da ONG'),
            preserve_default=False,
        ),
    ]
