# Generated by Django 5.0.4 on 2024-06-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_cadastromodel_cpf_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Instituicao",
            new_name="Ong",
        ),
    ]
