# Generated by Django 5.0.4 on 2024-06-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_instituicao_ong"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ong",
            new_name="Instituicao",
        ),
    ]
