# Generated by Django 5.0.4 on 2024-06-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_ong_instituicao"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Instituicao",
            new_name="Ong",
        ),
    ]
