# Generated by Django 5.0.4 on 2024-06-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_instituicao_ong"),
    ]

    operations = [
        migrations.AddField(
            model_name="ong",
            name="endereco",
            field=models.CharField(default="Endereço padrão", max_length=255),
        ),
        migrations.AddField(
            model_name="ong",
            name="horario_funcionamento",
            field=models.CharField(default="24 horas", max_length=100),
        ),
    ]
