# Generated by Django 5.0.4 on 2024-06-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_doacao_tipo_doacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doacao",
            name="tipo_doacao",
        ),
    ]
