# Generated by Django 5.0.4 on 2024-06-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_tipodoacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ong",
            name="tipo_doacao",
        ),
    ]
