# Generated by Django 5.0.4 on 2024-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_ong_tipo_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodoacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
