# Generated by Django 5.0.4 on 2024-06-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_tipodoacao_valor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tipodoacao",
            old_name="valor",
            new_name="valor_doacao",
        ),
    ]
