# Generated by Django 5.0.4 on 2024-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_tipodoacao_valor_doacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValorDoacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_doacao",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor da Doação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de Doação",
                "verbose_name_plural": "Valores de Doação",
            },
        ),
    ]
