# Generated by Django 5.0.4 on 2024-06-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_valordoacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodoacao',
            options={'verbose_name': 'Tipo de Doação', 'verbose_name_plural': 'Tipos de Doação'},
        ),
        migrations.RemoveField(
            model_name='tipodoacao',
            name='valor_doacao',
        ),
    ]
