# Generated by Django 5.0.4 on 2024-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_tipodoacao_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValorDoacao',
        ),
        migrations.AlterModelOptions(
            name='tipodoacao',
            options={},
        ),
        migrations.AlterField(
            model_name='tipodoacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Tipo de Doação'),
        ),
    ]
