# Generated by Django 5.0.4 on 2024-06-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
